#!/bin/sh
# Bash script to sync databases using maatkit
# Script by Marcelo Cavalcante - kalib - kalibslack@gmail.com
###############################################################

# Check parameters
if [ -z "$1" ]; then
	echo "Usage: `basename $0` host1 port1 user1 password1 host2 port2 user2 password2"
	exit 1
elif [ $# -ne 8 ]; then
	echo "Must use 8 parameters! Usage: `basename $0` host1 port1 user1 password1 host2 port2 user2 password2"
fi

# check two databases and store data into a file
#mk-table-checksum --ignore-databases mysql h=$1,u=$3,p=$4,P=$2 h=$5,u=$7,p=$8,P=$6 | mk-checksum-filter | grep -n "" >/tmp/chk.txt
~/bin/mk-table-checksum --ignore-databases mysql h=$1,u=$3,p=$4,P=$2 >> checksum_1.txt
~/bin/mk-table-checksum --ignore-databases mysql h=$5,u=$7,p=$8,P=$6 >> checksum_2.txt
mk-checksum-filter checksum_1.txt checksum_2.txt | grep -n "" >/tmp/chk.txt

# check the file and take what we need
l=`cat /tmp/chk.txt|cut -d: -f1|tail -1`
i="1"

if [ -z $l ] ; then
#echo "No sync need to be done."
exit 0
else
while [ $i -le $l ] ; do

# create two variables where v1 is the database name and v2 is the table
v1=`cat /tmp/chk.txt|grep $i:|sed s/:/\ /|awk '{print $2}'`
v2=`cat /tmp/chk.txt|grep $i:|sed s/:/\ /|awk '{print $3}'`

# execute the sync using our variables
mk-table-sync --execute D=$v1,t=$v2,h=$1,u=$3,p=$4,P=$2 h=$5,u=$7,p=$8,P=$6

i=`echo $i+1|bc`
done
#echo "I'm done. Your databases are synchronized now."
fi

#sleep 2s

exit 0
